const ChannelController=require('./../Controller/Channel.controller')
const SubscriptionController=require('./../Controller/SubScription.controller')
const routes=require('express').Router()
routes.post("/AddChannel",ChannelController.AddChannel)
routes.post("/AddSubscription",SubscriptionController.AddSubscription)
routes.post("/CheckSubscription",SubscriptionController.checkSubscribers)
routes.put("/editImage/:id",ChannelController.editChannelImage)
routes.get("/AddSubscriber/:_id",ChannelController.AddSubscriber)
routes.put("/EditChannelName",ChannelController.editChannelName)
routes.get("/RemoveSubscriber/:_id",ChannelController.removeSubscriber)
routes.put("/EditSocials",ChannelController.editSocial)
routes.get("/getAllChannel",ChannelController.GetAllChannel)
routes.get("/GetCreatorsCahnnel/:creator",ChannelController.getCreatorChannel)
routes.get("/GetOneChannel/:id",ChannelController.getOneChannel)
routes.get('/RemoveSubscription/:id',SubscriptionController.RemoveSubscription)
routes.get('/GetAllCreatorChannel/:id',ChannelController.getAllCreatorChannel)
routes.get('/GetSubscription/:id',SubscriptionController.getSubscription)

module.exports=routes