const routes=require('express').Router()
const ContentController=require("./../Controller/Content.controller")
const PlayListController=require("./../Controller/Playlist.controller")
const ReplyController=require('./../Controller/Reply.controller')
routes.post("/NewContent",ContentController.CreateNewContent)
routes.get("/AddLike/:id",ContentController.AddLikes)
routes.get("/AddDislikes/:id",ContentController.AddDislike)
routes.put("/AddReport/:id",ContentController.AddReportCount)
routes.put("/ChangeApproval",ContentController.ChangeApproval)
routes.put("/Content/AddTags/:id",ContentController.AddTags)
routes.put("/Content/DeleteTags/:id",ContentController.DeleteTags)
routes.post("/CreatePlaylist",PlayListController.AddPlayist)
routes.post("/Playlist/Video",PlayListController.AddVideoToPlaylist)
routes.post("/Video/AddReply/:id",ReplyController.AddReply)
routes.get("/Video/Reply/Like/:id",ReplyController.AddLike)
routes.get("/Video/Reply/RemoveLike/:id",ReplyController.RemoveLike)
routes.get("/video/Reply/Dislike/:id",ReplyController.RemoveDisLike)
routes.get("/video/Reply/RemoveDisLike/:id",ReplyController.RemoveDisLike)
routes.get("/GetChannel/:id",ContentController.getChannel)
routes.get("/GetContent",ContentController.GetContent)
routes.get("/GetOneContent/:id",ContentController.getOneContent)
routes.get("/GetCreator/:id",ContentController.getCreator)
module.exports=routes
