const routes=require('express').Router()
const UserController=require('./../Controller/User.Controller')
routes.post("/AddNewUser",UserController.RegisterUser)
routes.post("/VerifyMobile",UserController.RegisterUserMobile)
routes.post("/Login",UserController.LoginUser)
routes.post("/LoginMobile",UserController.LoginUserMobile)
routes.put("/RegisterMobile",UserController.SendOTP)
routes.put("/ResetPassWord",UserController.ResetPassword)
routes.put("/ForgotPassword",UserController.generateResetLink)
routes.put("/EditProfile",UserController.EditProfile)
routes.put("/EditContact",UserController.EditContact)
routes.post("/MakeCreator",UserController.BecomeCreator)
routes.get("/GetAll",UserController.getAlluser)
routes.get("/GetOne/:token",UserController.getOneUser)
module.exports=routes